[project]
name = 'bitcoin-mood-journal'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.bitcoin-mood-journal]
path = 'contracts/bitcoin-mood-journal.clar'
clarity_version = 2
epoch = 2.5

[contracts.mood-utils]
path = 'contracts/mood-utils.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
